only post
Signed-off-by: Chai <li.love.watching.shiba.inu@gmail.com>

diff --git a/.github/workflows/main-test.yml b/.github/workflows/main-test.yml
--- a/.github/workflows/main-test.yml
+++ b/.github/workflows/main-test.yml
@@ -11,15 +11,15 @@ jobs:
     runs-on: ubuntu-latest
 
     services:
-      redis:
-        image: redis
-        options: >-
-          --health-cmd "redis-cli ping"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          - 6379:6379
+      # redis:
+      #   image: redis
+      #   options: >-
+      #     --health-cmd "redis-cli ping"
+      #     --health-interval 10s
+      #     --health-timeout 5s
+      #     --health-retries 5
+      #   ports:
+      #     - 6379:6379
 
       postgres:
         image: postgres:14
@@ -33,38 +33,43 @@ jobs:
         ports:
           - 5432:5432
 
-      rabbitmq:
-        image: rabbitmq:3
-        env:
-          RABBITMQ_DEFAULT_USER: guest
-          RABBITMQ_DEFAULT_PASS: guest
-        options: >-
-          --health-cmd "rabbitmq-diagnostics -q ping"
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          - 5672:5672
+      # rabbitmq:
+      #   image: rabbitmq:3
+      #   env:
+      #     RABBITMQ_DEFAULT_USER: guest
+      #     RABBITMQ_DEFAULT_PASS: guest
+      #   options: >-
+      #     --health-cmd "rabbitmq-diagnostics -q ping"
+      #     --health-interval 10s
+      #     --health-timeout 5s
+      #     --health-retries 5
+      #   ports:
+      #     - 5672:5672
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-
-    - name: Install Nix
-      uses: DeterminateSystems/nix-installer-action@main
-
-    - name: Setup Nix Cache
-      uses: DeterminateSystems/magic-nix-cache-action@main
-
-    - name: Setup database and run tests
+    - name: Check PostgreSQL is running
       run: |
-        set -a
-        source env.ci
-        set +a
-        nix develop --command bash -c "
-          set -e
-          psql -h localhost -p 5432 -U postgres -c 'create database chafan_dev;'
-          PYTHONPATH=\$PWD alembic upgrade head
-          PYTHONPATH=\$PWD python scripts/initial_data.py
-          PYTHONPATH=\$PWD pytest chafan_core/tests -v
-        "
+        pg_isready -h localhost -p 5432 -U postgres
+        echo "PostgreSQL is up and running!"
+
+    # - name: Checkout
+    #   uses: actions/checkout@v4
+
+    # - name: Install Nix
+    #   uses: DeterminateSystems/nix-installer-action@main
+
+    # - name: Setup Nix Cache
+    #   uses: DeterminateSystems/magic-nix-cache-action@main
+
+    # - name: Setup database and run tests
+    #   run: |
+    #     set -a
+    #     source env.ci
+    #     set +a
+    #     nix develop --command bash -c "
+    #       set -e
+    #       psql -h localhost -p 5432 -U postgres -c 'create database chafan_dev;'
+    #       PYTHONPATH=\$PWD alembic upgrade head
+    #       PYTHONPATH=\$PWD python scripts/initial_data.py
+    #       PYTHONPATH=\$PWD pytest chafan_core/tests -v
+    #     "
